config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :members do
      collection do
        post :invite
      end
    end
    resources :artifacts
    resources :tasks
  end
  resources :accounts
  devise_for :users, controllers: { registrations: 'registrations' }

  match '/plan/edit/:id' => 'plans#edit', via: :get, as: :edit_plan
  match '/plan/update/:id' => 'plans#update', via: [:put, :patch], as: :update_plan


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root "home#index"
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :user
  validates_uniqueness_of :name
  validates_presence_of :name, :user_id
end

app/controllers/tasks_controller.rb
# app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, except: [:index, :new, :create]

  def index
    @tasks = @project.tasks
  end
    
  def show
    @task = Task.find(params[:id])
  end
    
  def new
   # @project = Project.find(params[:project_id])
    @task = @project.tasks.build
    @task.user_id = current_user.id
  end
    
    def create
      @task = @project.tasks.build(task_params)
      if current_user.admin?  # Assuming you have a method to check if the user can assign tasks
        @task.user_id = params[:task][:user_id]  # Assign the user_id based on the selected user
      else
        @task.user_id = current_user.id  # Assign the user_id to the current user if they cannot assign tasks
      end

      if @task.save
        redirect_to project_tasks_path(@task.project, @task), notice: 'Task was successfully created.'
      else
        respond_to do |format|
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
    end
    
    def edit
    end
    
    def update
      if @task.update(task_params)
        redirect_to project_tasks_path(@task.project), notice: 'Task was successfully updated.'
      else
        respond_to do |format|
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
    end
    
    def destroy
      @task.destroy
      redirect_to project_tasks_path(@task.project), notice: 'Task was successfully destroyed.'
    end
    
    private
    def set_project
      @project = Project.find(params[:project_id])
    end

  def set_task
    @task = Task.find(params[:id])
  end
    
  def task_params
    params.require(:task).permit(:name, :done, :project_id, :user_id)
  end

  def authorize_user
    unless current_user.admin? || @task.user == current_user
      redirect_to root_path, alert: 'You are not authorized to perform this action.'
    end
  end

end
  

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1 class="mt-5">Edit Task</h1>

      <%= form_with(model: [@task.project, @task], url: project_task_path(@task.project), class: "mt-3") do |form| %>
        <%= form.hidden_field :project_id, value: @task.project_id %>
        <% if current_user.admin? %>
          <div class="mb-3">
            <%= form.label :user_id, 'Assign to:', class: "form-label" %>
            <%= form.select :user_id, options_for_select(@task.project.members.map{ |member| [member.user.email, member.user.id] }, @task.user_id), { include_blank: true }, { class: "form-select" } %>
          </div>
        <% else %>
          <%= form.hidden_field :user_id, value: current_user.id %>
        <% end %>

        <% if @task.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
            <h2 class="alert-heading"><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
            <ul>
              <% @task.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="mb-3">
          <%= form.label :name, class: "form-label" %>
          <%= form.text_field :name, class: "form-control" %>
        </div>

        <div class="mb-3">
          <h3>
          <%= form.label :done, class: "form-check-label" %>
          <%= form.check_box :done, class: "border form-check-input", id: "done_check" %>
          </h3>
        </div>

        <div class="mb-3">
          <%= form.submit "Save Task", class: "btn btn-primary" %>
        </div>
      <% end %>

      <%= link_to 'Back To Tasks', project_tasks_path(params[:project_id]), class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Done</th>
      <th>Project</th>
      <th>Assign to/Created by</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <% if current_user.admin? || task.user == current_user %>
        <tr>
          <td <% if task.done %>style="text-decoration: line-through;"<% end %>><%= task.name %></td>
          <td><%= task.done ? 'Yes' : 'No' %></td>
          <td><%= task.project.name %></td>
          <td><%= task.user.email %></td>
          <td>
            <%= link_to 'Show', project_task_path(task.project, task), class: 'btn btn-secondary btn-sm' %>
            <%= link_to 'Edit', edit_project_task_path(task.project, task), class: 'btn btn-secondary btn-sm ms-1' %>
            <%= link_to "Delete", project_task_path(task.project, task), class: "btn btn-danger btn-sm ms-1", style: "display: inline-block;", data: { turbo_method: :delete, "turbo-confirm": "Are you sure you want to delete this Task?" } %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Task', new_project_task_path, class: "btn btn-primary" %>
<div>
  <%= link_to 'Back to Project', project_path(@project), class: "btn btn-secondary mt-3" %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<div class="row">
  <div class="col-md-6">
    <%= form_with(model: [@task.project, @task], url: project_tasks_path(@task.project), class: "mt-4") do |form| %>
      <%= form.hidden_field :project_id, value: @task.project_id %>
      <% if current_user.admin? %>
        <div class="mb-3">
          <%= form.label :user_id, 'Assign to:', class: "form-label" %>
          <%= form.collection_select :user_id, @task.project.members, :user_id, lambda { |member| member.user.email }, { include_blank: true }, { class: "form-select" } %>
        </div>
      <% else %>
        <%= form.hidden_field :user_id, value: current_user.id %>
      <% end %>

      <% if @task.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <h2 class="alert-heading"><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
          <ul>
            <% @task.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-3">
        <%= form.label :Task, class: "form-label" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="mb-3">
        <h3>
        <%= form.label :done, class: "form-check-label" %>
        <%= form.check_box :done, class: "border form-check-input", id: "done_check" %>
        </h3>
      </div>


      <div class="mb-3">
        <%= form.submit "Save Task", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

<%= link_to 'Back To Tasks', project_tasks_path(params[:project_id]), class: "btn btn-secondary" %>

app/views/tasks/show.html.erb
<div class="row">
  <div class="col-md-6 card mt-3">
    <div class="card-body">

      <p class="card-text">
        <strong>Name:</strong>
        <% if @task.done %>
          <span style="text-decoration: line-through;"><%= @task.name %></span>
        <% else %>
          <%= @task.name %>
        <% end %>
      </p>

      <p class="card-text">
        <strong>Done:</strong>
        <%= @task.done ? 'Yes' : 'No' %>
      </p>

      <p class="card-text">
        <strong>Project :</strong>
        <%= @task.project.name %>
      </p>

      <p class="card-text">
        <strong>Assign to / Created by :</strong>
        <%= @task.user.email %>
      </p>

    </div>
  </div>
</div>

<div class="mt-3">
  <%= link_to 'Edit Task', edit_project_task_path(@task.project, @task), class: 'btn btn-primary' %> 
  <%= link_to 'Back To Task', project_tasks_path(@task.project), class: 'btn btn-secondary ms-3' %>
</div>
  <%= link_to "Destroy this account", project_task_path(@task.project, @task), class: "btn btn-danger btn-block mt-3", style: "display: inline-block;", data: { turbo_method: :delete, "turbo-confirm": "Are you sure you want to delete this Account?" } %>