config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :members do
      collection do
        post :invite
      end
    end
    resources :artifacts
    resources :tasks
  end
  resources :accounts
  devise_for :users, controllers: { registrations: 'registrations' }

  match '/plan/edit/:id' => 'plans#edit', via: :get, as: :edit_plan
  match '/plan/update/:id' => 'plans#update', via: [:put, :patch], as: :update_plan


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root "home#index"
end

app/models/project.rb
class Project < ApplicationRecord
  acts_as_tenant :account
  belongs_to :account

  attr_accessor :plan

  validates_uniqueness_of :name, scope: :account_id, if: :name_changed? # scope use for mantain uniqueness only in tenant
  validate :free_plan_can_only_have_one_project, on: :create

  has_many :tasks, dependent: :destroy
  has_many :artifacts, dependent: :destroy
  has_many :members, dependent: :destroy
  has_many :users, through: :members # Assuming roles are associated with members

  # Set limit of project according to plan
  def free_plan_can_only_have_one_project
    if account.plan == 'free' && account.projects.count >= 1 && !premium_plan?
      errors.add(:base, "Free plan can have only one project")
    end
  end
  
  def premium_plan?
    account.plan == 'premium'
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authorize_member, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    begin
      @projects = current_user.projects
      # show errer if you don't have tenant of 
    rescue ActsAsTenant::Errors::NoTenantSet
      flash[:alert] = "You do not have a tenant. Please set a tenant before access."
      redirect_to root_path
    end
  end

  # GET /projects/1 or /projects/1.json
  def show
    @project = Project.find(params[:id])
    @artifacts = @project.artifacts
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        @project.members.create(user: current_user, roles: {admin: true})
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.members.destroy_all # Delete associated members

    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      project_id = params[:id]
      flash[:alert] = "You are not have Project with Project ID #{project_id}."
      redirect_to projects_path
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:account_id, :name, :details, :expected_completion_date)
    end

    # Check project member Authorization
    def authorize_member
      return redirect_to root_path, alert: 'You are not a member' unless @project.users.include? current_user
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_with(model: project) do |form| %>
      <% if project.errors.any? %>
        <div style="color: red;">
          <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

          <ul>
            <% project.errors.full_messages.each do |error_message| %>
              <li><%= error_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group mt-3">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group mt-3">
        <%= form.label :details %>
        <%= form.text_area :details, class: 'form-control' %>
      </div>

      <div class="form-group col-md-4 mt-3">
        <%= form.label :expected_completion_date %>
        <%= form.date_field :expected_completion_date, class: 'form-control' %>
      </div>

      <div class="form-group mt-3">
        <%= form.submit 'Save Project', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>" class="card mt-3">
  <div class="card-body">
    <p class="card-text">
      <strong>Tenant Domain :</strong> <%= project.account.domain %>
    </p>

    <p class="card-text">
      <strong>Project Name :</strong> <%= project.name %>
    </p>

    <p class="card-text">
      <strong>Project Details :</strong> <%= project.details %>
    </p>

    <p class="card-text">
      <strong>Expected Completion Date :</strong> <%= project.expected_completion_date %>
    </p>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="row">
  <div class="col-mb-6">
    <h1>Editing project</h1>
    <%= render "form", project: @project %>
    <br>
    <div>
      <%= link_to "Show this project", @project , class: "btn btn-primary btn-block"%> 
      <%= link_to "Back to projects", projects_path, class: "btn btn-secondary btn-block" %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<%- model_class = Project -%>

<div class="page-header">
  <h1><%=t '.name', default: model_class.model_name.human.pluralize.titleize %></h1>
</div>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:details) %></th>
      <th><%= model_class.human_attribute_name(:expected_completion_date) %></th>
      <th><%=t '.actions', default: t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project_path(project) %></td>
        <td><%= project.details %></td>
        <td><%= project.expected_completion_date %></td>
        <td>
          <%= link_to 'Show Project', project_path(project), class: 'btn btn-secondary btn-xs' %>
          
          <% if current_user.admin? %>
            <%= link_to t('.edit', default: t("helpers.links.edit")), edit_project_path(project), class: 'btn btn-secondary btn-xs' %>
            <%= link_to "Destroy Project", project_path(project), class: "btn btn-xs btn-danger ", data: { turbo_method: :delete, "turbo-confirm": "Are you sure you want to delete this Project?" } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%# TODO:- if plan hit limit new project button will hide %>
<%= link_to 'New Project', new_project_path, class: 'btn btn-primary' %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path, class: "btn btn-secondary btn-block" %>
</div>

app/views/projects/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-8">
      <%= render @project %>
    </div>
</div>

    <div class="col-md-4">
      <div class="mt-3">
        <%= link_to "Back to projects", projects_path, class: "btn btn-secondary btn-block m-2 " %>
        <% if current_user.admin? %>
          <%= link_to "Edit this project", edit_project_path(@project), class: "btn btn-primary btn-block m-2 ms-0" %>
          <%= link_to "Destroy this Project", project_path(@project), class: "btn btn-danger btn-block mb-2", style: "display: inline-block;", data: { turbo_method: :delete, "turbo-confirm": "Are you sure you want to delete this Project?" } %>
        <% end %>
      </div>

      <%= link_to "Members", project_members_path(@project), class: "btn btn-primary btn-block me-2" %>
      <%= link_to "Artifacts", project_artifacts_path(@project), class: "btn btn-secondary btn-block me-2" %>
      <%= link_to 'Tasks', project_tasks_path(@project), class: "btn btn-info btn-block" %>
    </div>
  </div>

  <%= render 'artifacts/list', locals: { project: @project, artifact: @artifact } %>