config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :members do
      collection do
        post :invite
      end
    end
    resources :artifacts
    resources :tasks
  end
  resources :accounts
  devise_for :users, controllers: { registrations: 'registrations' }

  match '/plan/edit/:id' => 'plans#edit', via: :get, as: :edit_plan
  match '/plan/update/:id' => 'plans#update', via: [:put, :patch], as: :update_plan


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root "home#index"
end

app/models/artifact.rb
class Artifact < ApplicationRecord
  belongs_to :project
  has_one_attached :file


  MAX_FILESIZE = 10.megabytes
  validates_presence_of :name, :file
  validates_uniqueness_of :name
  
  # custom validation for file size
  validate :uploaded_file_size
  
  private

  def uploaded_file_size
    if file.attached? && file.blob.byte_size > self.class::MAX_FILESIZE
      errors.add(:file, "File size must be less than #{self.class::MAX_FILESIZE}")
    end
  end

end

app/controllers/artifacts_controller.rb
class ArtifactsController < ApplicationController
  before_action :set_artifact, only: %i[ show edit update destroy ]

  # GET /artifacts or /artifacts.json
  def index
    @project = Project.find(params[:project_id])
    @artifacts = @project.artifacts
  end

  # GET /artifacts/1 or /artifacts/1.json
  def show
    @artifact = Artifact.find(params[:id])
    @project = @artifact.project
    @file = @artifact.file
  end

  # GET /artifacts/new
  def new
    @project = Project.find(params[:project_id])
    @artifact = Artifact.new
  end

  # GET /artifacts/1/edit
  def edit
    @artifact = Artifact.find(params[:id])
    @project = Project.find(params[:project_id])
  end

  # POST /artifacts or /artifacts.json
  def create
    @project = Project.find(params[:project_id])
    @artifact = @project.artifacts.build(artifact_params)

    respond_to do |format|
      if @artifact.save
        format.html { redirect_to project_artifacts_path(@project), notice: "Artifact was successfully created." }
        format.json { render :show, status: :created, location: @artifact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artifacts/1 or /artifacts/1.json
  def update
    @artifact = Artifact.find(params[:id])
    @project = @artifact.project

    respond_to do |format|
      if @artifact.update(artifact_params)
        format.html { redirect_to project_artifacts_path(@project), notice: "Artifact was successfully updated." }
        format.json { render :show, status: :ok, location: @artifact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artifacts/1 or /artifacts/1.json
  def destroy
    @artifact.destroy!

    respond_to do |format|
      format.html { redirect_to project_artifacts_url, notice: "Artifact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artifact
      @artifact = Artifact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artifact_params
      params.require(:artifact).permit(:name, :project_id, :file)
    end
end

app/helpers/artifacts_helper.rb
module ArtifactsHelper
end

app/views/artifacts/_artifact.html.erb
<div id="<%= dom_id artifact %>">
  <p>
    <strong>Project Name :</strong>
    <%= artifact.project.name %>
  </p>

  <p>
    <strong>Artifact Name :</strong>
    <%= artifact.name %>
  </p>

  <p>
    <strong>File:</strong>
  </p>

  <% if @file.attached? %>
    <% if @file.content_type.start_with?('image') %>
      <%= image_tag @file, width: "100%", height: "100%" %>
    <% elsif @file.content_type.start_with?('video') %>
      <video width="80%" height="80%" controls>
        <source src="<%= rails_blob_path(@file) %>" type="<%= @file.content_type %>">
        Your browser does not support the video tag.
      </video>
      <br><%= link_to "Download Video 💾", rails_blob_path(@file, disposition: "attachment"), class: "btn btn-info m-3 ms-0" %>
    <% elsif @file.content_type.start_with?('audio') %>
      <audio controls>
        <source src="<%= rails_blob_path(@file) %>" type="<%= @file.content_type %>">
        Your browser does not support the audio element.
      </audio>
      <br><%= link_to "Download Audio 🎵", rails_blob_path(@file, disposition: "attachment"), class: "btn btn-info m-3 ms-0" %>
    <% elsif @file.content_type == 'application/pdf' %>
      <iframe src="<%= rails_blob_path(@file, disposition: "inline") %>" width="100%" height="400"></iframe>
      <%= link_to "Download PDF 💾", rails_blob_path(@file, disposition: "attachment"), class: "btn btn-info m-3 ms-0"%>
      <%= link_to "Show Full PDF🔎", artifact.file, class: "btn btn-info m-3 ms-0" %>
    <% elsif @file.content_type == 'application/vnd.ms-powerpoint' || @file.content_type == 'application/vnd.openxmlformats-officedocument.presentationml.presentation' || @file.content_type == 'application/vnd.ms-powerpoint.presentation.macroenabled.12' %>
      <%= link_to "View PowerPoint Presentation 📊", rails_blob_path(@file, disposition: "inline"), class: "btn btn-info m-3 ms-0" %>
      <%= link_to "Download PowerPoint 💾", rails_blob_path(@file, disposition: "attachment"), class: "btn btn-info m-3 ms-0" %>
    <% elsif @file.content_type == 'application/vnd.oasis.opendocument.spreadsheet' || @file.content_type == 'application/vnd.ms-excel' || @file.content_type == 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' || @file.content_type == 'application/vnd.ms-excel.sheet.macroenabled.12' %>
      <%= link_to "View Spreadsheet 📊", rails_blob_path(@file, disposition: "inline"), class: "btn btn-info m-3 ms-0" %>
      <%= link_to "Download Spreadsheet 💾", rails_blob_path(@file, disposition: "attachment"), class: "btn btn-info m-3 ms-0" %>
    <% else %>
      <% if @file.blob.filename.present? %>
        <%= link_to "Download File 💾", rails_blob_path(@file, disposition: "attachment"), class: "btn btn-info m-3 ms-0" %>
      <% else %>
        <p>Unsupported file type</p>
      <% end %>
    <% end %>
  <% else %>
    <p>No file attached</p>
  <% end %>
</div>

app/views/artifacts/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_with(model: [project, artifact], url: project_artifacts_path(project)) do |form| %>
      <% if artifact.errors.any? %>
        <div style="color: red;">
          <h2><%= pluralize(artifact.errors.count, "error") %> prohibited this artifact from being saved:</h2>

          <ul>
            <% artifact.errors.full_messages.each do |error_message| %>
              <li><%= error_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group mt-3">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group mt-3">
        <%= form.label :upload, value: 'File to upload' %>
        <%= form.file_field :file, class: 'form-control' %>
      </div>
      <%= form.hidden_field :project_id%>
      <div class="form-group mt-3">
        <%= form.submit 'Save Artifacts', class: 'btn btn-primary' %>
      </div>
      <%# <%= link_to 'Cancle', project_path(project_id: current_project_id, id: @artifact.project_id), class: 'btn btn-secondary btn-xs' %>
    <% end %>
  </div>
</div>

app/views/artifacts/_list.html.erb
<div class="row">
  <div class="col-md-9">
    <% model_class = Artifact %>
    <h3 class="mt-3">Artifacts</h3>
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:name) %></th>
          <th><%= model_class.human_attribute_name(:file) %></th>
          <th><%= t '.actions', default: t("helpers.actions") %></th>
        </tr>
      </thead>
      <tbody>
        <% @artifacts.each do |artifact| %>
          <tr>
            <td><%= artifact.name %></td>
            <td> 
              <% if artifact.file.attached? %>
                <%= link_to artifact.file.filename, artifact.file %>
              <% else %>
                No file attached
              <% end %>
            </td>
            <td>
              <%= link_to 'Show', project_artifact_path(@project, artifact), class: 'btn btn-secondary' %>
              <% if current_user.admin? %>
                <%= link_to 'Edit', edit_project_artifact_path(@project, artifact), class: 'btn btn-primary ms-1' %>
                <%= link_to 'Destroy Artifact', project_artifact_path(artifact.project, artifact), class: 'btn btn-danger ms-1', style: 'display: inline-block;', data: { turbo_method: :delete, 'turbo-confirm': 'Are you sure you want to delete this Artifact?' } %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'New artifact', new_project_artifact_path(@project), class: 'btn btn-primary mb-3' %>
  </div>
</div>

app/views/artifacts/edit.html.erb
<h1>Editing artifact</h1>

<div class="row">
  <div class="col-md-6">
    <%= form_with(model: [@project, @artifact], url: project_artifact_path(@project, @artifact), method: "patch") do |form| %>
      <% if @artifact.errors.any? %>
        <div style="color: red;">
          <h2><%= pluralize(@artifact.errors.count, "error") %> prohibited this artifact from being saved:</h2>

          <ul>
            <% @artifact.errors.full_messages.each do |error_message| %>
              <li><%= error_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group mt-3">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group mt-3">
        <%= form.label :upload, value: 'File to upload' %>
        <%= form.file_field :file, class: 'form-control' %>
      </div>
      <%= form.hidden_field :project_id%>
      <div class="form-group mt-3">
        <%= form.submit 'Save Artifacts', class: 'btn btn-success' %>
      </div>
      <%# <%= link_to 'Cancle', project_path(project_id: current_project_id, id: @artifact.project_id), class: 'btn btn-secondary btn-xs' %>
    <% end %>
  </div>
</div>

<br>

<div>
  <%= link_to "Show this artifact", project_artifact_path(@project, @artifact), class: 'btn btn-primary' %>
  <%= link_to "Back to artifacts", project_artifacts_path, class: 'btn btn-secondary ms-3'%>
</div>

app/views/artifacts/index.html.erb
<%= render 'artifacts/list' %>

<%= link_to 'Back to Project', project_path(@project), class: 'btn btn-secondary mt-3' %>

app/views/artifacts/new.html.erb
<h1>New artifact</h1>

<%= render 'form', project: @project, artifact: @artifact %>

<br>

<div>
  <%= link_to "Back to artifacts", project_artifacts_path(@project), class: 'btn btn-secondary' %>
</div>

app/views/artifacts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @artifact %>

<div>
  <%= link_to "Back to artifacts", project_artifacts_path, class: "btn btn-secondary " %>

<% if current_user.admin? %>
  <%= link_to "Edit this artifact", edit_project_artifact_path(@project, @artifact), class: "btn btn-primary me-3" %>
</div>

<div>
  <%= link_to "Destroy this Artifact", project_artifact_path(@artifact.project, @artifact), class: "btn btn-danger  mt-3 mb-5", style: "display: inline-block;", data: { turbo_method: :delete, "turbo-confirm": "Are you sure you want to delete this Artifact?" } %>
</div>
<% end %>