config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :members do
      collection do
        post :invite
      end
    end
    resources :artifacts
    resources :tasks
  end
  resources :accounts
  devise_for :users, controllers: { registrations: 'registrations' }

  match '/plan/edit/:id' => 'plans#edit', via: :get, as: :edit_plan
  match '/plan/update/:id' => 'plans#update', via: [:put, :patch], as: :update_plan


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root "home#index"
end

app/models/account.rb
class Account < ApplicationRecord
  validates_uniqueness_of :name, :domain, :subdomain
  validates_presence_of :domain, :subdomain
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
  has_many :projects, dependent: :destroy
  has_one :payment, dependent: :destroy
  accepts_nested_attributes_for :payment

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]
  # GET /accounts or /accounts.json
  def index
    @accounts = current_user.accounts
  end

  # GET /accounts/1 or /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)
    @account.creator_id = current_user.id # Assign current user's ID as creator_id

    respond_to do |format|
      if @account.save
        format.html { redirect_to account_url(@account), notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to account_url(@account), notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    ActsAsTenant.without_tenant do
      @account.destroy!

      respond_to do |format|
        format.html { redirect_to accounts_url, notice: "Account was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  private


    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:name, :subdomain, :domain)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account.html.erb
<div id="<%= dom_id account %>" class="card mt-3">
  <div class="card-body">
    <p class="card-text">
      <strong>Name:</strong> <%= account.name %>
    </p>

    <p class="card-text">
      <strong>Subdomain:</strong> <%= account.subdomain %>
    </p>

    <p class="card-text">
      <strong>Domain:</strong> <%= account.domain %>
    </p>

    <p class="card-text">
      <strong>Plan:</strong> <%= account.plan %>
    </p>
  </div>
</div>

app/views/accounts/_form.html.erb
<%= form_with(model: account, class: "row g-3") do |form| %>
  <% if account.errors.any? %>
    <div class="col-md-6" style="color: red">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <%= form.label :name, class: "form-label", style: "display: block" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <%= form.label :subdomain, class: "form-label", style: "display: block" %>
      <%= form.text_field :subdomain, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <%= form.label :domain, class: "form-label", style: "display: block" %>
      <%= form.text_field :domain, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <%= form.submit "Submit", class: "btn btn-success m-3 ms-0" %>
    </div>
  </div>

<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Show this account", @account, class: "btn btn-primary" %>
  <%= link_to "Back to accounts", accounts_path, class: "btn btn-secondary ms-3" %>
</div>

app/views/accounts/index.html.erb
<h1>Accounts</h1>

<table class="table table-bordered table-hover mt-2">
  <thead>
    <tr>
      <th>Name</th>
      <th>Subdomain</th>
      <th>Domain</th>
      <th>Plan</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.name %></td>
        <td><%= account.subdomain %></td>
        <td><%= account.domain %></td>
        <td><%= account.plan %></td>
        <td>
          <%= link_to "Show", account, class: "btn btn-primary btn-sm" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New account", new_account_path, class: "btn btn-success" %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Back to accounts", accounts_path, class: "btn btn-secondary"  %>
</div>

app/views/accounts/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-6">
      <%= render @account %>
    </div>
</div>

<div>
  <%= link_to "Edit this account", edit_account_path(@account), class: "btn btn-primary btn-block m-2 ms-0" %>
  <%= link_to "Back to accounts", accounts_path, class: "btn btn-secondary btn-block m-2 " %>
<br>
  <%= link_to "Destroy this account", @account, class: "btn btn-danger btn-block mb-2", style: "display: inline-block;", data: { turbo_method: :delete, "turbo-confirm": "Are you sure you want to delete this Account?" } %>
</div>

 <%= link_to "Edit Plan", edit_plan_path, class: "btn btn-info" %>